### ISSUE TITLE
2.30.2 broke my FakeValkey setup: Valkey.__init__() got an unexpected keyword argument 'redis_connect_func'

### ISSUE THREAD

**Issue by LasseGravesenSaxo** [cunla/fakeredis-py#400]
**Describe the bug**
After upgrading fakeredis from 2.30.1 to 2.30.2, I now get this error when I try to setup a FakeValkey:

```python
Traceback (most recent call last):
  File "/home/USER/Workspace/fakeredis-test/main.py", line 9, in <module>
    main()
    ~~~~^^
  File "/home/USER/Workspace/fakeredis-test/main.py", line 4, in main
    fake_valkey = fakeredis.FakeValkey()
  File "/home/USER/Workspace/fakeredis-test/.venv/lib/python3.13/site-packages/fakeredis/_valkey.py", line 19, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/USER/Workspace/fakeredis-test/.venv/lib/python3.13/site-packages/fakeredis/_connection.py", line 167, in __init__
    super().__init__(**kwds)
    ~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: Valkey.__init__() got an unexpected keyword argument 'redis_connect_func'. Did you mean 'valkey_connect_func'?
```

**To Reproduce**
1) Install fakeredis[valkey]
2) Add main.py file:
```python
import fakeredis

def main():
    fake_valkey = fakeredis.FakeValkey()
    fake_valkey.set("key1", "value1")

if __name__ == "__main__":
    main()
```
3) Run `python main.py`

**Expected behavior**
I expect no errors and that it sets key1 to value1 in the setup.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - python version: 3.13.3
 - redis-py version: 2.30.2
 - full requirements.txt:
```
fakeredis==2.30.2
    # via fakeredis-test
redis==6.2.0
    # via fakeredis
sortedcontainers==2.4.0
    # via fakeredis
valkey==6.1.0
    # via fakeredis
```

**Additional context**
