### ISSUE TITLE
The newest release 2.26.0 does not work with Python 3.7

### ISSUE THREAD

**Issue by not522** [cunla/fakeredis-py#341]
**Describe the bug**
Thanks for your great project!
I found the newest release 2.26.0 does not work with Python 3.7.

**To Reproduce**
```python
>>> import fakeredis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/not/.pyenv/versions/fakeredis/lib/python3.7/site-packages/fakeredis/__init__.py", line 3, in <module>
    from ._connection import (
  File "/Users/not/.pyenv/versions/fakeredis/lib/python3.7/site-packages/fakeredis/_connection.py", line 8, in <module>
    from ._server import FakeBaseConnectionMixin, FakeServer, VersionType
  File "/Users/not/.pyenv/versions/fakeredis/lib/python3.7/site-packages/fakeredis/_server.py", line 6, in <module>
    from typing import Dict, Tuple, Any, List, Optional, Union, Literal
ImportError: cannot import name 'Literal' from 'typing' (/Users/not/.pyenv/versions/3.7.8/lib/python3.7/typing.py)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - python version: 3.7.8
 - redis-py version: 2.26.0
 - full requirements.txt?

**Additional context**

**Comment by kloczek** [comment]
Python 3.7 is already EOSed https://endoflife.date/python.

**Comment by cunla** [comment]
While it is not officially supported, I can publish a fix for this.

**Comment by cunla** [comment]
Will publish a fix soon.

**Comment by cunla** [comment]
Released.
